^window grab$: user.screenshot_window()
^screen grab$: user.screenshot()
^selection grab$: user.screenshot_selection()
^window clip$: user.screenshot_window_clipboard()
^screen clip$: user.screenshot_clipboard()