window new: app.window_open()
window next: app.window_next()
window last: app.window_previous()
window close: app.window_close()
focus <user.running_applications>: user.switcher_focus(running_applications)
window list: user.switcher_list_running()
window list hide: user.switcher_hide_running()
