arrow: "->"
dub arrow: "=>"
new line: "\\n"
carriage return: "\\r"
line feed: "\\r\\n"
(a sign|asign|assign): " = "
minus: " - "
plus: " + "
times: " * "

divide: " / "
modulus: " % "
minus equals: " -= "
plus equals: " += "
greater: " > "
lesser: " < "
equal: " == "
not equal: " != "
greater equal: " >= "
less equal: " <= "
to power: " ** "
lodge and: " && "
lodge or: " || "
bit and: " & "
bit or: " | "
ex or: " ^ "
shift left: " << "
shift right: " >> "
and equal: " &= "
or equals: " |= "
